#!/bin/bash
# Debconf config script for airtime

set -e

db_input high airtime/apache-setup || true
db_go ||true

db_get airtime/apache-setup
if [ "$RET" = "dedicated v-host" ]; then
	db_input high airtime/apache-servername || true
	db_go ||true
	db_input high airtime/apache-serveradmin || true
	db_go ||true
fi

#DEBHELPER#

exit 0
