#!/bin/bash
#postinst script for airtime

set -e

. /usr/share/debconf/confmodule

if [ "$DPKG_DEBUG" = "developer" ]; then
    set -x
fi

WEB_USER=www-data
WEB_GROUP=www-data

package_name="airtime"
datadir="/srv/${package_name}"
wwwdir="/var/lib/${package_name}"
configdir="/etc/airtime"
includefile="${configdir}/apache.conf"
a2tplfile="${configdir}/apache.vhost.tpl"
phpinifile="${configdir}/airtime.ini"
OLDVERSION="$2"

case "$1" in
  configure|reconfigure)

    #webserver=`echo $webserver|sed -e 's/,  */ /g'`
    webserver="apache2"
    php="php5"
    dohtaccess=""

		test -e ${wwwdir}/airtime_mvc || ln -s ${wwwdir} ${wwwdir}/airtime_mvc

    #  clean up previous configurations
    if [ -L /etc/$webserver/conf.d/airtime.conf ]; then
      rm -f /etc/$webserver/conf.d/airtime.conf || true
      restart="$webserver $restart"
    fi
    if [ -f /etc/$webserver/sites-available/airtime-vhost ]; then
      a2dissite airtime-vhost &>/dev/null || true
      restart="$webserver $restart"
    fi

    # APACHE config
    db_get airtime/apache-setup
    if [ "$RET" == "system-wide (all vhosts)" ]; then
      if [ ! -d /etc/$webserver/conf.d/ ]; then
        install -d -m755 /etc/$webserver/conf.d/
      fi
      if [ ! -e /etc/$webserver/conf.d/airtime.conf ]; then
        ln -s ${includefile} /etc/$webserver/conf.d/airtime.conf
        restart="$webserver $restart"
      fi
			a2enmod rewrite &>/dev/null || true
      dohtaccess="/airtime"
    elif [ "$RET" == "dedicated v-host" ]; then
      db_get airtime/apache-servername
      SN=$RET
      db_get airtime/apache-serveradmin
      SA=$RET

      if [ ! -d /etc/$webserver/sites-available/ ]; then
        install -d -m755 /etc/$webserver/sites-available/
      fi
      sed -e "s/__SERVER_ADMIN__/${SA}/;s/__SERVER_NAME__/${SN}/" \
        ${a2tplfile} > /etc/$webserver/sites-available/airtime-vhost
      a2ensite airtime-vhost &>/dev/null
			a2enmod rewrite &>/dev/null || true
      restart="$webserver $restart"
      dohtaccess="/"
    fi

    db_get airtime/apache-deldefault
    if [ "$RET" == "remove default" ]; then
      a2dissite default || true
      a2dissite 000-default || true
    fi

    # PHP config
    if [ ! -d /etc/$php/conf.d/ ]; then
      install -d -m755 /etc/$php/conf.d/
    fi
    if [ ! -e /etc/$php/conf.d/airtime.ini ]; then
      ln -s ${phpinifile} /etc/$php/conf.d/airtime.ini
      restart="$webserver $restart"
    fi

    # install additional pear module
    pear channel-discover pear.phing.info || true
    pear install phing/phing-2.4.2 || true
    pip install kombu || true
    pip install poster || true

    # .htaccess file
    echo -ne "/RewriteBase/d\nwq\n\n" \
    | ed /var/lib/airtime/.htaccess &>/dev/null || true

    if [ -n "${dohtaccess}" ]; then
      echo -ne "/RewriteEngine/\n+1i\n    RewriteBase ${dohtaccess}\n.\nwq\n" \
      | ed /var/lib/airtime/.htaccess &>/dev/null || true
    fi

    # XXX ICECAST XXX
    db_get airtime/icecast-setup
    if [ "$RET" == "true" ]; then
      if [ -f /etc/default/icecast2 -a -f /etc/icecast2/icecast.xml ]; then
        echo "Setting up icecast2.." >&2
        echo -ne "%s/^.*ENABLE=.*$/ENABLE=true/\nwq\n" \
        | ed /etc/default/icecast2 &>/dev/null || true
        db_get airtime/icecast-sourcepw
        ICESOURCE=$RET
        db_get airtime/icecast-relaypw
        ICERELAY=$RET
        db_get airtime/icecast-adminpw
        ICEADMIN=$RET
        echo -ne "%s/<source-password>[^<]*</source-password>/<source-password>$ICESOURCE</source-password>/\n%s/<relay-password>[^<]*</relay-password>/<relay-password>$ICERELAY</relay-password>/\n%s/<admin-password>[^<]*</admin-password>/<admin-password>$ICEADMIN</admin-password>/\nwq\n" \
        | ed /etc/icecast2/icecast.xml &>/dev/null || true
        invoke-rc.d icecast2 restart || true
        # save source-password in airtime
        echo -ne "%s/~password=\"[^\"]*\"/~password=\"$ICESOURCE\"/\nwq\n" \
        | ed /var/lib/airtime/python_apps/pypo/scripts/library/shoutcast.liq &>/dev/null || true
        echo -ne "%s/^.*icecast_pass.*$/icecast_pass = \"$ICESOURCE\"/\nwq\n" \
        | ed /var/lib/airtime/python_apps/pypo/scripts/liquidsoap.cfg &>/dev/null || true
      else
        echo "Icecast not installed" >&2
      fi
    fi

    # Monit setup
    db_get airtime/monit-setup
    if [ "$RET" == "true" ]; then
      if [ -f /etc/default/monit ]; then
        echo "Setting up monit.." >&2
         echo -ne "%s/^.*startup=.*$/startup=1/\nwq\n" | ed /etc/default/monit &>/dev/null || true
          cp /var/lib/airtime/python_apps/monit/airtime-monit.cfg /etc/monit/conf.d
           grep -q "include /etc/monit/conf.d" /etc/monit/monitrc
           RETVAL=$?
           if [ $RETVAL -ne 0 ] ; then
           echo "include /etc/monit/conf.d/*" >> /etc/monit/monitrc
           fi
            invoke-rc.d monit restart || true
      else
        echo "Monit not installed" >&2
      fi
    fi

    # create data dir
    mkdir -p $datadir

    # Permissions
    #dpkg-statoverride --list $datadir &>/dev/null || \
    #dpkg-statoverride --add --force --update $WEB_USER $WEB_GROUP 0755 $datadir
    #dpkg-statoverride --list $datadir/conf &>/dev/null || \
    #dpkg-statoverride --add --force --update $WEB_USER $WEB_GROUP 0750 $datadir/conf

    dpkg-statoverride --list $datadir &>/dev/null || \
    dpkg-statoverride --add --force --update $WEB_USER $WEB_GROUP 0750 $datadir

    servers="apache2"
    . /usr/share/wwwconfig-common/restart.sh
    echo $error >&2

		if [ "${OLDVERSION:0:3}" = "1.7" -o "${OLDVERSION:0:3}" = "1.8" ]; then
			cd $wwwdir/install_minimal/ && ./airtime-install
		else
			cd $wwwdir/install_minimal/ && ./airtime-install -o
		fi

  ;;

  abort-upgrade|abort-remove|abort-deconfigure)

  ;;

  *)
       echo "postinst called with unknown argument \`$1'" >&2
       exit 1
  ;;
esac

#DEBHELPER#

exit 0
