#!/bin/bash
#postrm script for airtime

set -e

if [ -f /usr/share/debconf/confmodule ]; then
  . /usr/share/debconf/confmodule
fi

if [ "$DPKG_DEBUG" = "developer" ]; then
    set -x
fi

package_name="airtime"
datadir="/srv/airtime"
wwwdir="/var/lib/airtime"
configdir="/etc/airtime"

webserver="apache2"
php="php5"

case "$1" in
  purge|remove)

		if [ -L ${wwwdir}/airtime_mvc ]; then
			rm -f ${wwwdir}/airtime_mvc || true
		fi

		rm -f ${wwwdir}/.htaccess || true

		if [ -f ${wwwdir}/install_minimal/distribute-0.6.10.tar.gz ]; then
			rm -f ${wwwdir}/install_minimal/distribute-0.6.10.tar.gz || true
		fi

		# airtime uninstaller does not remove these
                if [ -d ${wwwdir}/python_apps/pypo/liquidsoap_bin ]; then
			rm -rf ${wwwdir}/python_apps/pypo/liquidsoap_bin || true
		fi

                if [ -d ${wwwdir}/python_apps/pypo/liquidsoap ]; then
                        rm -rf ${wwwdir}/python_apps/pypo/liquidsoap || true
                fi

                if [ -d ${wwwdir}/install_minimal/upgrades/airtime-1.9.0/airtimefilemonitor ]; then
                        rm -rf ${wwwdir}/install_minimal/upgrades/airtime-1.9.0/airtimefilemonitor || true
                fi

                if [ -f ${wwwdir}/install_minimal/upgrades/airtime-1.9.0/storDump.txt ]; then
                        rm -f ${wwwdir}/install_minimal/upgrades/airtime-1.9.0/storDump.txt || true
                fi

    # Un-configure webservers
    if [ -L /etc/$webserver/conf.d/airtime.conf ]; then
      rm -f /etc/$webserver/conf.d/airtime.conf || true
      restart="$webserver $restart"
    fi

    if [ -L /etc/$php/conf.d/airtime.ini ]; then
      rm -f /etc/$php/conf.d/airtime.ini || true
      restart="$webserver $restart"
    fi

    if [ -f /etc/$webserver/sites-available/airtime-vhost ]; then
      a2dissite airtime-vhost &>/dev/null || true
      # TODO: if airtime-vhost is not modified -> delete it
      restart="$webserver $restart"
    fi

    servers="apache2"
    # may not exist if package was manually installed
    if [ -r /usr/share/wwwconfig-common/restart.sh ]; then
      . /usr/share/wwwconfig-common/restart.sh
      echo $error
    fi

    # Permissions
    #dpkg-statoverride --list $datadir/conf &>/dev/null && \
    #dpkg-statoverride --remove $datadir/conf || true

    dpkg-statoverride --list $datadir &>/dev/null && \
    dpkg-statoverride --remove $datadir || true

    if [ "$1" = "purge" ]; then
                        echo "Purge specified, removing configuration files" >&2
			rm -rf /etc/airtime || true
                        db_purge
     			#pear uninstall phing/phing-2.4.2 || true
		 	#pip uninstall kombu || true
		 	#pip uninstall poster || true
    fi

  ;;

  upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)

  ;;

  *)
      echo "postrm called with unknown argument \`$1'" >&2
      exit 1
  ;;
esac

#DEBHELPER#

exit 0
