#!/bin/bash
#postinst script for airtime

set -e

. /usr/share/debconf/confmodule

if [ "$DPKG_DEBUG" = "developer" ]; then
    set -x
fi

WEB_USER=www-data
WEB_GROUP=www-data

package_name="airtime"
datadir="/srv/airtime"
wwwdir="/usr/share/airtime"
tmpdir="/var/lib/airtime/tmp"
configdir="/etc/airtime"
includefile="${configdir}/apache.conf"
a2tplfile="${configdir}/apache.vhost.tpl"
phpinifile="${configdir}/airtime.ini"
OLDVERSION="$2"
NEWVERSION="1.9.4"

case "$1" in
  configure|reconfigure)

    webserver="apache2"
    php="php5"

    #  clean up previous configurations
    if [ -L /etc/$webserver/conf.d/airtime.conf ]; then
      rm -f /etc/$webserver/conf.d/airtime.conf
    fi

    if [ -f /etc/$webserver/sites-available/airtime-vhost ]; then
      a2dissite airtime-vhost
    fi

    # this file in 1.8.2 is a directory path in 1.9.3
    if [ -f /var/www/airtime/utils/airtime-import ]; then
      rm -f /var/www/airtime/utils/airtime-import
    fi

    # Install phing
    echo "Installing phing..."
    command -v pear > /dev/null
    RETVAL=$?
    if [ $RETVAL -eq 0 ]; then
     pear channel-discover pear.phing.info || true
     pear install phing/phing-2.4.2 || true
    fi

    # APACHE config
    echo "Setting up apache2..."

    # create the document root if it doesn't exist
    if [ ! -d $wwwdir/public/ ]; then
      install -d -m755 $wwwdir/public/
    fi

    # set up the virtual host
    db_get airtime/apache-setup
    if [ "$RET" == "system-wide (all vhosts)" ]; then
      if [ ! -d /etc/$webserver/conf.d/ ]; then
        install -d -m755 /etc/$webserver/conf.d/
      fi
      if [ ! -e /etc/$webserver/conf.d/airtime.conf ]; then
        ln -s ${includefile} /etc/$webserver/conf.d/airtime.conf
      fi

    elif [ "$RET" == "dedicated v-host" ]; then
      db_get airtime/apache-servername
      SN=$RET
      db_get airtime/apache-serveradmin
      SA=$RET

      if [ ! -d /etc/$webserver/sites-available/ ]; then
        install -d -m755 /etc/$webserver/sites-available/
      fi
      sed -e "s/__SERVER_ADMIN__/${SA}/;s/__SERVER_NAME__/${SN}/" \
        ${a2tplfile} > /etc/$webserver/sites-available/airtime-vhost

      command -v a2ensite > /dev/null
      RETVAL=$?
      if [ $RETVAL -eq 0 ]; then
      a2ensite airtime-vhost
      fi
    fi

    # enable the rewrite module
    command -v a2enmod > /dev/null
    RETVAL=$?
    if [ $RETVAL -eq 0 ]; then
      a2enmod rewrite
    fi

    # remove the default site, if requested to
    db_get airtime/apache-deldefault
    if [ "$RET" == "remove default" ]; then
      if [ -f /etc/apache2/sites-available/default ]; then
      a2dissite default
      fi
    fi

    # PHP config
    echo "Configuring php5..."
    if [ ! -d /etc/$php/conf.d/ ]; then
      install -d -m755 /etc/$php/conf.d/
    fi
    if [ ! -e /etc/$php/conf.d/airtime.ini ]; then
      ln -s ${phpinifile} /etc/$php/conf.d/airtime.ini
    fi

    # XXX ICECAST XXX
    db_get airtime/icecast-setup
    if [ "$RET" == "true" ]; then
      if [ -f /etc/default/icecast2 -a -f /etc/icecast2/icecast.xml ]; then
        echo "Setting up icecast2..."
        echo -ne "%s/^.*ENABLE=.*$/ENABLE=true/\nwq\n" | ed /etc/default/icecast2
        db_get airtime/icecast-sourcepw
        ICESOURCE=$RET
        sed -i "s:<source-password>.*<\/source-password>:<source-password>$ICESOURCE<\/source-password>:g" /etc/icecast2/icecast.xml
        db_get airtime/icecast-relaypw
        ICERELAY=$RET
        sed -i "s:<relay-password>.*<\/relay-password>:<relay-password>$ICERELAY<\/relay-password>:g" /etc/icecast2/icecast.xml
        db_get airtime/icecast-adminpw
        ICEADMIN=$RET
        sed -i "s:<admin-password>.*<\/admin-password>:<admin-password>$ICEADMIN<\/admin-password>:g" /etc/icecast2/icecast.xml
        db_get airtime/icecast-hostname
        ICEHOST=$RET
        sed -i "s:<hostname>.*<\/hostname>:<hostname>$ICEHOST<\/hostname>:g" /etc/icecast2/icecast.xml

        # restart icecast server
        invoke-rc.d icecast2 restart || true

          # save icecast hostname and source-password in airtime
          db_get airtime/icecast-hostname
          ICEHOST=$RET
          echo -ne "%s/^.*icecast_host.*$/icecast_host = \"$ICEHOST\"/\nwq\n" \
          | ed ${tmpdir}/python_apps/pypo/liquidsoap_scripts/liquidsoap.cfg
            if [ -f ${wwwdir}/python_apps/pypo/liquidsoap_scripts/liquidsoap.cfg ]; then
            echo -ne "%s/^.*icecast_host.*$/icecast_host = \"$ICEHOST\"/\nwq\n" \
            | ed ${wwwdir}/python_apps/pypo/liquidsoap_scripts/liquidsoap.cfg
            fi
          db_get airtime/icecast-sourcepw
          ICESOURCE=$RET
          echo -ne "%s/^.*icecast_pass.*$/icecast_pass = \"$ICESOURCE\"/\nwq\n" \
          | ed ${tmpdir}/python_apps/pypo/liquidsoap_scripts/liquidsoap.cfg
            if [ -f ${wwwdir}/python_apps/pypo/liquidsoap_scripts/liquidsoap.cfg ]; then
            echo -ne "%s/^.*icecast_pass.*$/icecast_pass = \"$ICESOURCE\"/\nwq\n" \
            | ed ${wwwdir}/python_apps/pypo/liquidsoap_scripts/liquidsoap.cfg
            fi

            # on reconfigure or upgrade, also update the liquidsoap.cfg file and restart playout
            if [ -f /etc/airtime/liquidsoap.cfg ]; then
            db_get airtime/icecast-hostname
            ICEHOST=$RET
            echo -ne "%s/^.*icecast_host.*$/icecast_host = \"$ICEHOST\"/\nwq\n" \
            | ed /etc/airtime/liquidsoap.cfg
            db_get airtime/icecast-sourcepw
            ICESOURCE=$RET
            echo -ne "%s/^.*icecast_pass.*$/icecast_pass = \"$ICESOURCE\"/\nwq\n" \
            | ed /etc/airtime/liquidsoap.cfg
              if [ -f /etc/init.d/airtime-playout ]; then
              invoke-rc.d airtime-playout restart
              fi
            fi
      else
        echo "The icecast2 package does not appear to be installed on this server."
      fi
    fi

    # Monit setup
      if [ -f /etc/default/monit ]; then
        echo "Setting monit configuration..."
         sed -i 's:startup=.*:startup=1:g' /etc/default/monit
          cp ${tmpdir}/python_apps/monit/airtime-monit.cfg /etc/monit/conf.d

           MONITCONFIGURED=$(grep "include /etc/monit/conf.d" /etc/monit/monitrc || true)
           if [ -z "$MONITCONFIGURED" ]; then
            echo "include /etc/monit/conf.d/*" >> /etc/monit/monitrc
           fi

            invoke-rc.d monit restart
      else
        echo "The monit package does not appear to be installed on this server."
      fi

    # Local timezone setup
    db_get airtime/localtime-setup
     LOCALTIMEZONE=$RET
      if [ -f ${tmpdir}/airtime_mvc/public/.htaccess ]; then
        echo "Setting local time zone..."
         sed -i "s:php_value date.timezone \".*\":php_value date.timezone \"$LOCALTIMEZONE\":g" ${tmpdir}/airtime_mvc/public/.htaccess
      else
       if [ -f ${wwwdir}/public/.htaccess ]; then
        echo "Updating local time zone..."
         sed -i "s:php_value date.timezone \".*\":php_value date.timezone \"$LOCALTIMEZONE\":g" ${wwwdir}/public/.htaccess
        else
       echo ".htaccess file not found"
       fi
      fi

    # stop debconf so daemons started by the install script cannot hold open the pipe
    db_stop

    # start rabbitmq if it isn't running
    if [ -f /etc/init.d/rabbitmq-server ]; then
      RABBITMQSTOPPED=$(invoke-rc.d rabbitmq-server status | grep no_nodes_running || true)
        if [ -n "$RABBITMQSTOPPED" ]; then
           invoke-rc.d rabbitmq-server start
        fi

        # Warn if rabbitmq is installed but not set to start on boot
        RABBITMQSTARTONBOOT=$(ls /etc/rc2.d/ | grep rabbitmq || true)
          if [ -z "$RABBITMQSTARTONBOOT" ]; then
            echo "Warning: rabbitmq-server is not configured to start after a reboot!"
            echo "Fix Default-Start and Default-Stop lines in /etc/init.d/rabbitmq-server"
            echo "then run this command as root: update-rc.d rabbitmq-server defaults"
          fi
    else
     echo "The rabbitmq-server package does not appear to be installed on this server."
    fi

    # create data dir
    mkdir -p $datadir

    dpkg-statoverride --list $datadir || true
    dpkg-statoverride --add --force --update $WEB_USER $WEB_GROUP 0750 $datadir

    # restart apache
    invoke-rc.d apache2 restart

    # don't run airtime-install if the user is doing a dpkg-reconfigure
    if [ "$1" = "reconfigure" ] || [ -n "$DEBCONF_RECONFIGURE" ] ; then
      echo "Reconfiguration complete."
    else

      if [ "${OLDVERSION:0:3}" = "1.6" ]; then
        echo "Upgrades from Airtime versions before 1.7.0 are not supported. Please back up your files and perform a clean install."
      else

        mkdir -p /var/log/airtime
        cd $tmpdir/install_minimal/

        if [ "${OLDVERSION:0:5}" == "${NEWVERSION}" ] ; then
          echo "Reinstallation detected..."
          echo | ./airtime-install -rp 2> /var/log/airtime/reinstallation-errors.log
        else

          ./airtime-install 2> /var/log/airtime/installation-errors.log

        fi
      fi
    fi
  ;;

  abort-upgrade|abort-remove|abort-deconfigure)

  ;;

  *)
       echo "postinst called with unknown argument \`$1'" >&2
       exit 1
  ;;
esac

#DEBHELPER#

exit 0
