#!/bin/bash
#postrm script for airtime

set -e

if [ -f /usr/share/debconf/confmodule ]; then
  . /usr/share/debconf/confmodule
fi

if [ "$DPKG_DEBUG" = "developer" ]; then
    set -x
fi

package_name="airtime"
datadir="/var/lib/${package_name}"
configdir="/etc/airtime"

webserver="apache2"
php="php5"

case "$1" in
  purge|remove)

    # Un-configure webservers
    if [ -L /etc/$webserver/conf.d/airtime.conf ]; then
      rm -f /etc/$webserver/conf.d/airtime.conf || true
      restart="$webserver $restart"
    fi
        
    if [ -L /etc/$php/conf.d/airtime.ini ]; then
      rm -f /etc/$php/conf.d/airtime.ini || true
      restart="$webserver $restart"
    fi

    if [ -f /etc/$webserver/sites-available/airtime-vhost ]; then
      a2dissite airtime-vhost &>/dev/null || true
      # TODO: if airtime-vhost is not modified -> delete it
      restart="$webserver $restart"
    fi
        
    servers="apache2"
    # may not exist if package was manually installed
    if [ -r /usr/share/wwwconfig-common/restart.sh ]; then
      . /usr/share/wwwconfig-common/restart.sh
      echo $error
    fi

    # Permissions
    #dpkg-statoverride --list $datadir/conf &>/dev/null && \
    #dpkg-statoverride --remove $datadir/conf || true

    dpkg-statoverride --list $datadir/files &>/dev/null && \
    dpkg-statoverride --remove $datadir/files || true

    if [ "$1" = "purge" ]; then
		 #rm -rf $datadir || true
     #pear uninstall phing/phing-2.4.2 || true
		 #pip uninstall kombu || true
		 #pip uninstall poster  || true
		 true
    fi
                                                                                                                                             
  ;;

  upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)

  ;;

  *)
      echo "postrm called with unknown argument \`$1'" >&2
      exit 1
  ;;
esac

#DEBHELPER#

exit 0
