#!/bin/bash
#prerm script for airtime

set -e

package_name="airtime"
datadir="/usr/share/${package_name}/"

case "$1" in
  remove|purge)
      cd $datadir/ && ./uninstall || true
  ;;

  upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
  ;;

  *)
      echo "prerm called with unknown argument \`$1'" >&2
      exit 1
  ;;
esac

#DEBHELPER#

exit 0
