#!/bin/bash
#prerm script for airtime

set -e

package_name="airtime"
datadir="/var/lib/${package_name}"

case "$1" in
  purge|remove)
                                                                                                                                             
      cd $datadir/install/ && php airtime-uninstall.php
  ;;

  upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)

  ;;

  *)
      echo "postrm called with unknown argument \`$1'" >&2
      exit 1
  ;;
esac

#DEBHELPER#

exit 0
